<?php
return Settings::extend('item',array(
	'list'=>array(
		'create'=>array(
			/*'person',
			'project'*/
		),
		'list'=>array(
			/*'person',
			'project'*/
		),
		/*'filter'=>Settings::lock(array(
			'type'=>array(
				'type'=>'option',
				'operators'=>array(
					'='
				),
				'options'=>array(
					'person',
					'project'
				),
			))
		),*/
	),
));