<?php
return Settings::extend('item',array(
	'alias'=>array(
		'module'=>TRUE,
		'global'=>TRUE
	),
	'version'=>FALSE,
	'module'=>':module',
	'controller'=>':module',
	'model'=>':module',
	'form'=>':module',
	'viewer'=>':module',
	'view'=>array(
		'list'=>'item/list',
		'create'=>'item/create',
		'update'=>'item/update',
		'version'=>'item/version',
		'close'=>'item/close',
	),
	'list'=>array(
		'type'=>'table',
		'selectable'=>FALSE,
		'sortable'=>FALSE,
		'batch'=>array(),
		'hidable'=>TRUE,
		'create'=>TRUE,
		'view'=>array(
			'tools'=>'list/item/tools',
			'show_hide'=>'list/item/show_hide'
		),
		'tools'=>array(
			'update',
			'delete',
			'preview'=>array(
				'icon'=>'search',
				'attributes'=>array('target'=>'_blank'),
				'acl'=>FALSE
			)
		),
		'keys'=>array(
			'timestamp'=>array(
				'view'=>'timestamp',
				'width'=>150
			),
			'title'=>array(
				'action'=>'update',
			)
		),
		'sort'=>array(
			'title'=>'ASC',
			'timestamp'=>'DESC'
		),
		'filter'=>array(
			'title'=>array(
				'type'=>'text',
				'operators'=>array(
					'LIKE',
				)
			),
			'timestamp'=>array(
				'type'=>'number',
				'operators'=>array(
					'=',
					'>',
					'<',
				)
			),
			'status'=>array(
				'type'=>'option',
				'operators'=>array(
					'='
				),
				'options'=>array(
					Model_Item::STATUS_EDIT,
					Model_Item::STATUS_LIVE
				),
			),
			'created'=>array(
				'type'=>'date',
				'operators'=>array(
					'<',
					'>',
					'=',
				),
			),
			'owner_id'=>array(
				'type'=>'relation',
				'operators'=>array(
					'=',
					'<>',
				),
				'model'=>'User',
				'field'=>'username'
			)
		),
		'pagination'=>array(
			'step'=>30
		)
	),
));